### ISSUE TITLE
Status of this plugin?

### ISSUE THREAD

**Issue by Ciantic** [jgoz/typescript-loader#3]
I know this is not a forum, but I felt uneasy to spam webpack Issue about this even though there is this [long Issue thread](https://github.com/webpack/webpack/issues/61) that kind of turned to support forum for your plugin.

I decided to open this. My question what is the status? Is it usable? 

Thanks and :+1: for the good work so far.

**Comment by jgoz** [comment]
Please note that this loader is deprecated in favour of [andreypopp/typescript-loader](https://github.com/andreypopp/typescript-loader), which uses the newly exposed Language Services API in typescript 1.4. The npm package will be published from that repository in the near future.
